apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gob-gab
  name: nginx-config
data:
  default.conf: | 
    server {
      listen 80;
      server_name_;
      location / {
        default_type application/json;
        return 200 "Monchavin Pinthong";
      }
    }